// Generated by gencpp from file ros_noetic_service_demo/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_NOETIC_SERVICE_DEMO_MESSAGE_ADDTWOINTS_H
#define ROS_NOETIC_SERVICE_DEMO_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_noetic_service_demo/AddTwoIntsRequest.h>
#include <ros_noetic_service_demo/AddTwoIntsResponse.h>


namespace ros_noetic_service_demo
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_noetic_service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_noetic_service_demo::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_noetic_service_demo::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_noetic_service_demo::AddTwoInts > {
  static const char* value()
  {
    return "ros_noetic_service_demo/AddTwoInts";
  }

  static const char* value(const ::ros_noetic_service_demo::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_noetic_service_demo::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_noetic_service_demo::AddTwoInts >
template<>
struct MD5Sum< ::ros_noetic_service_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_noetic_service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::ros_noetic_service_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_noetic_service_demo::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_noetic_service_demo::AddTwoInts >
template<>
struct DataType< ::ros_noetic_service_demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_noetic_service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::ros_noetic_service_demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_noetic_service_demo::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_noetic_service_demo::AddTwoInts >
template<>
struct MD5Sum< ::ros_noetic_service_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_noetic_service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::ros_noetic_service_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_noetic_service_demo::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_noetic_service_demo::AddTwoInts >
template<>
struct DataType< ::ros_noetic_service_demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_noetic_service_demo::AddTwoInts >::value();
  }
  static const char* value(const ::ros_noetic_service_demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_NOETIC_SERVICE_DEMO_MESSAGE_ADDTWOINTS_H
